
package telecom.mss.jt.cg_cgfz;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SICGFZSVRRETURNMESSAGEOUTSynService", targetNamespace = "urn:telecom:mss:jt:cg-cgfz", wsdlLocation = "http://192.168.167.181/mdmws/services/returnMessageOutSyn?wsdl")
public class SICGFZSVRRETURNMESSAGEOUTSynService
    extends Service
{

    private final static URL SICGFZSVRRETURNMESSAGEOUTSYNSERVICE_WSDL_LOCATION;
    private final static WebServiceException SICGFZSVRRETURNMESSAGEOUTSYNSERVICE_EXCEPTION;
    private final static QName SICGFZSVRRETURNMESSAGEOUTSYNSERVICE_QNAME = new QName("urn:telecom:mss:jt:cg-cgfz", "SICGFZSVRRETURNMESSAGEOUTSynService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.167.181/mdmws/services/returnMessageOutSyn?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SICGFZSVRRETURNMESSAGEOUTSYNSERVICE_WSDL_LOCATION = url;
        SICGFZSVRRETURNMESSAGEOUTSYNSERVICE_EXCEPTION = e;
    }

    public SICGFZSVRRETURNMESSAGEOUTSynService() {
        super(__getWsdlLocation(), SICGFZSVRRETURNMESSAGEOUTSYNSERVICE_QNAME);
    }

    public SICGFZSVRRETURNMESSAGEOUTSynService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SICGFZSVRRETURNMESSAGEOUTSYNSERVICE_QNAME, features);
    }

    public SICGFZSVRRETURNMESSAGEOUTSynService(URL wsdlLocation) {
        super(wsdlLocation, SICGFZSVRRETURNMESSAGEOUTSYNSERVICE_QNAME);
    }

    public SICGFZSVRRETURNMESSAGEOUTSynService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SICGFZSVRRETURNMESSAGEOUTSYNSERVICE_QNAME, features);
    }

    public SICGFZSVRRETURNMESSAGEOUTSynService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SICGFZSVRRETURNMESSAGEOUTSynService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SICGFZSVRRETURNMESSAGEOUTSyn
     */
    @WebEndpoint(name = "SI_CGFZSVR_RETURN_MESSAGE_OUT_SynPort")
    public SICGFZSVRRETURNMESSAGEOUTSyn getSICGFZSVRRETURNMESSAGEOUTSynPort() {
        return super.getPort(new QName("urn:telecom:mss:jt:cg-cgfz", "SI_CGFZSVR_RETURN_MESSAGE_OUT_SynPort"), SICGFZSVRRETURNMESSAGEOUTSyn.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SICGFZSVRRETURNMESSAGEOUTSyn
     */
    @WebEndpoint(name = "SI_CGFZSVR_RETURN_MESSAGE_OUT_SynPort")
    public SICGFZSVRRETURNMESSAGEOUTSyn getSICGFZSVRRETURNMESSAGEOUTSynPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:telecom:mss:jt:cg-cgfz", "SI_CGFZSVR_RETURN_MESSAGE_OUT_SynPort"), SICGFZSVRRETURNMESSAGEOUTSyn.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SICGFZSVRRETURNMESSAGEOUTSYNSERVICE_EXCEPTION!= null) {
            throw SICGFZSVRRETURNMESSAGEOUTSYNSERVICE_EXCEPTION;
        }
        return SICGFZSVRRETURNMESSAGEOUTSYNSERVICE_WSDL_LOCATION;
    }

}
