
package telecom.mss.jt.cg_cgfz;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import telecom.mss.jt.cgfz.EIACBACKRESPONSE;
import telecom.mss.jt.cgfz.ObjectFactory;
import telecom.mss.jt.cgfz.PROVIDER;
import telecom.mss.jt.cgfz.PURHCASEORDERBACKREQUEST;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_CGFZSVR_RETURN_MESSAGE_OUT_Syn", targetNamespace = "urn:telecom:mss:jt:cg-cgfz")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SICGFZSVRRETURNMESSAGEOUTSyn {


    /**
     * 
     * @param iREQUEST
     * @return
     *     returns telecom.mss.jt.cgfz.EIACBACKRESPONSE
     */
    @WebMethod(operationName = "XXX_MT_PROVIDER_FEEDBACK")
    @WebResult(name = "E_RESPONSE", targetNamespace = "")
    @RequestWrapper(localName = "XXX_MT_PROVIDER_FEEDBACK", targetNamespace = "urn:telecom:mss:jt:cgfz", className = "telecom.mss.jt.cgfz.XXXMTPROVIDERFEEDBACK")
    @ResponseWrapper(localName = "XXX_MT_PROVIDER_FEEDBACKResponse", targetNamespace = "urn:telecom:mss:jt:cgfz", className = "telecom.mss.jt.cgfz.XXXMTPROVIDERFEEDBACKResponse")
    public EIACBACKRESPONSE xxxMTPROVIDERFEEDBACK(
        @WebParam(name = "I_REQUEST", targetNamespace = "")
        PROVIDER iREQUEST);

    /**
     * 
     * @param iREQUEST
     * @return
     *     returns telecom.mss.jt.cgfz.EIACBACKRESPONSE
     */
    @WebMethod(operationName = "XXX_MT_PURCHASE_ORDER_BACK")
    @WebResult(name = "E_RESPONSE", targetNamespace = "")
    @RequestWrapper(localName = "XXX_MT_PURCHASE_ORDER_BACK", targetNamespace = "urn:telecom:mss:jt:cgfz", className = "telecom.mss.jt.cgfz.XXXMTPURCHASEORDERBACK")
    @ResponseWrapper(localName = "XXX_MT_PURCHASE_ORDER_BACKResponse", targetNamespace = "urn:telecom:mss:jt:cgfz", className = "telecom.mss.jt.cgfz.XXXMTPURCHASEORDERBACKResponse")
    public EIACBACKRESPONSE xxxMTPURCHASEORDERBACK(
        @WebParam(name = "I_REQUEST", targetNamespace = "")
        PURHCASEORDERBACKREQUEST iREQUEST);

    /**
     * 
     * @param iREQUEST
     * @return
     *     returns telecom.mss.jt.cgfz.EIACBACKRESPONSE
     */
    @WebMethod(operationName = "XXX_MT_MATCONFIG_FEEDBACK")
    @WebResult(name = "E_RESPONSE", targetNamespace = "")
    @RequestWrapper(localName = "XXX_MT_MATCONFIG_FEEDBACK", targetNamespace = "urn:telecom:mss:jt:cgfz", className = "telecom.mss.jt.cgfz.XXXMTMATCONFIGFEEDBACK")
    @ResponseWrapper(localName = "XXX_MT_MATCONFIG_FEEDBACKResponse", targetNamespace = "urn:telecom:mss:jt:cgfz", className = "telecom.mss.jt.cgfz.XXXMTMATCONFIGFEEDBACKResponse")
    public EIACBACKRESPONSE xxxMTMATCONFIGFEEDBACK(
        @WebParam(name = "I_REQUEST", targetNamespace = "")
        PROVIDER iREQUEST);

    /**
     * 
     * @param iREQUEST
     * @return
     *     returns telecom.mss.jt.cgfz.EIACBACKRESPONSE
     */
    @WebMethod(operationName = "XXX_MT_CHANGE_PURCHASE_ORDER_BACK")
    @WebResult(name = "E_RESPONSE", targetNamespace = "")
    @RequestWrapper(localName = "XXX_MT_CHANGE_PURCHASE_ORDER_BACK", targetNamespace = "urn:telecom:mss:jt:cgfz", className = "telecom.mss.jt.cgfz.XXXMTCHANGEPURCHASEORDERBACK")
    @ResponseWrapper(localName = "XXX_MT_CHANGE_PURCHASE_ORDER_BACKResponse", targetNamespace = "urn:telecom:mss:jt:cgfz", className = "telecom.mss.jt.cgfz.XXXMTCHANGEPURCHASEORDERBACKResponse")
    public EIACBACKRESPONSE xxxMTCHANGEPURCHASEORDERBACK(
        @WebParam(name = "I_REQUEST", targetNamespace = "")
        PURHCASEORDERBACKREQUEST iREQUEST);

    /**
     * 
     * @param iREQUEST
     * @return
     *     returns telecom.mss.jt.cgfz.EIACBACKRESPONSE
     */
    @WebMethod(operationName = "XXX_MT_MATERIAL_FEEDBACK")
    @WebResult(name = "E_RESPONSE", targetNamespace = "")
    @RequestWrapper(localName = "XXX_MT_MATERIAL_FEEDBACK", targetNamespace = "urn:telecom:mss:jt:cgfz", className = "telecom.mss.jt.cgfz.XXXMTMATERIALFEEDBACK")
    @ResponseWrapper(localName = "XXX_MT_MATERIAL_FEEDBACKResponse", targetNamespace = "urn:telecom:mss:jt:cgfz", className = "telecom.mss.jt.cgfz.XXXMTMATERIALFEEDBACKResponse")
    public EIACBACKRESPONSE xxxMTMATERIALFEEDBACK(
        @WebParam(name = "I_REQUEST", targetNamespace = "")
        PROVIDER iREQUEST);

}
