
package telecom.mss.jt.cg_cgfz;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SIMDMSVRMATERIALINAsynService", targetNamespace = "urn:telecom:mss:jt:cg-cgfz", wsdlLocation = "http://192.168.167.181/mdmws/services/mdmMaterialAsyn?wsdl")
public class SIMDMSVRMATERIALINAsynService
    extends Service
{

    private final static URL SIMDMSVRMATERIALINASYNSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIMDMSVRMATERIALINASYNSERVICE_EXCEPTION;
    private final static QName SIMDMSVRMATERIALINASYNSERVICE_QNAME = new QName("urn:telecom:mss:jt:cg-cgfz", "SIMDMSVRMATERIALINAsynService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.167.181/mdmws/services/mdmMaterialAsyn?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIMDMSVRMATERIALINASYNSERVICE_WSDL_LOCATION = url;
        SIMDMSVRMATERIALINASYNSERVICE_EXCEPTION = e;
    }

    public SIMDMSVRMATERIALINAsynService() {
        super(__getWsdlLocation(), SIMDMSVRMATERIALINASYNSERVICE_QNAME);
    }

    public SIMDMSVRMATERIALINAsynService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIMDMSVRMATERIALINASYNSERVICE_QNAME, features);
    }

    public SIMDMSVRMATERIALINAsynService(URL wsdlLocation) {
        super(wsdlLocation, SIMDMSVRMATERIALINASYNSERVICE_QNAME);
    }

    public SIMDMSVRMATERIALINAsynService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIMDMSVRMATERIALINASYNSERVICE_QNAME, features);
    }

    public SIMDMSVRMATERIALINAsynService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIMDMSVRMATERIALINAsynService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIMDMSVRMATERIALINAsyn
     */
    @WebEndpoint(name = "SI_MDMSVR_MATERIAL_IN_AsynPort")
    public SIMDMSVRMATERIALINAsyn getSIMDMSVRMATERIALINAsynPort() {
        return super.getPort(new QName("urn:telecom:mss:jt:cg-cgfz", "SI_MDMSVR_MATERIAL_IN_AsynPort"), SIMDMSVRMATERIALINAsyn.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIMDMSVRMATERIALINAsyn
     */
    @WebEndpoint(name = "SI_MDMSVR_MATERIAL_IN_AsynPort")
    public SIMDMSVRMATERIALINAsyn getSIMDMSVRMATERIALINAsynPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:telecom:mss:jt:cg-cgfz", "SI_MDMSVR_MATERIAL_IN_AsynPort"), SIMDMSVRMATERIALINAsyn.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIMDMSVRMATERIALINASYNSERVICE_EXCEPTION!= null) {
            throw SIMDMSVRMATERIALINASYNSERVICE_EXCEPTION;
        }
        return SIMDMSVRMATERIALINASYNSERVICE_WSDL_LOCATION;
    }

}
