
package telecom.mss.jt.cg_cgfz;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_MDMSVR_MATERIAL_IN_Asyn", targetNamespace = "urn:telecom:mss:jt:cg-cgfz")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIMDMSVRMATERIALINAsyn {


    /**
     * 
     * @param mtMATERIALCREATE
     */
    @WebMethod(operationName = "OP_MaterialCreate", action = "http://sap.com/xi/WebService/soap1.1")
    @Oneway
    public void opMaterialCreate(
        @WebParam(name = "MT_MATERIAL_CREATE", targetNamespace = "urn:telecom:mss:jt:cg-cgfz", partName = "MT_MATERIAL_CREATE")
        DTMATERIALCREATE mtMATERIALCREATE);

    /**
     * 
     * @param mtMATERIALFROZEN
     */
    @WebMethod(operationName = "OP_MaterialForzen", action = "http://sap.com/xi/WebService/soap1.1")
    @Oneway
    public void opMaterialForzen(
        @WebParam(name = "MT_MATERIAL_FROZEN", targetNamespace = "urn:telecom:mss:jt:cg-cgfz", partName = "MT_MATERIAL_FROZEN")
        DTMATERIALFROZEN mtMATERIALFROZEN);

}
